# Generated by Django 3.1.3 on 2023-06-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230607_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_choices',
            field=models.IntegerField(default=1),
        ),
    ]
